# 05 开始日志和异常处理

```py
'''
DebugLog 日志 和 错误 处理
'''

from urllib import request
from urllib import error

# 开启日志
'''
httpHandler = request.HTTPHandler(debuglevel=1)
httpsHandler = request.HTTPSHandler(debuglevel=1)

opener = request.build_opener(httpHandler, httpsHandler)
request.install_opener(opener)

res = request.urlopen("http://edu.51cto.com")

res.read()
'''

# 异常处理常规写法

'''
try:
    # request.urlopen("http://blog.csdn.net1")
    response = request.urlopen("http://www.python.org/")
except error.HTTPError as e:
    print(e.code)
    print(e.reason)
except error.URLError as e:
    #  URLError 没有 code 属性
    print(e.reason)
else:
    print("good!")
    print(response.read().decode("utf8"))
'''

'''
URLError

- 服务器无法连接
- 网址不存在
- 无网络
- HTTPError

HTTPError 是 URLError 的子类, 主要处理服务器连接成功后,返回的错误

'''


# 整合写法

try:
    # request.urlopen("http://blog.csdn.net1")
    response = request.urlopen("http://www.python.org1/")
except error.URLError as e:
    #  URLError 没有 code 属性
    if hasattr(e, "code"):
        print(e.code)
    if hasattr(e, "reason"):
        print(e.reason)
else:
    print("good!")
    print(response.read().decode("utf8"))
```